import {useState} from 'react';
import {Modal} from './ui';
const topics=[
 ['Vhosts and onboarding','Create a vhost with its customer domains and origins. Choose HTTP or HTTPS independently for the origin connection. Save queues deployment to active POPs; check each node’s applied state and job errors before directing DNS traffic there. Cache policies, rate limits, trusted client IPs and headers are reusable policies under Vhosts.'],
 ['HTTPS at the POP','For browser HTTPS with CDN caching, select a certificate covering every domain in the vhost TLS tab. Upload the full certificate chain and matching private key, or request a managed Certbot certificate. The browser connects to the POP: a certificate installed only on the origin cannot secure this connection. HTTP on port 80 is unencrypted and browsers correctly label it Not secure.'],
 ['Certbot and DNS','HTTP-01 requires the domain’s public A/AAAA records to reach the POPs on port 80. First deploy the vhost, point DNS to the POP addresses, wait for propagation, then request the certificate with an ACME email. Edgeplane distributes the challenge token to the active POPs. Wildcards need DNS-01 and access to the authoritative DNS API. Enable HTTPS redirects after the certificate has been deployed successfully.'],
 ['Origin TLS and passthrough','Automatic HTTPS mode uses the selected POP certificate, otherwise it passes encrypted TCP through to HTTPS origins. The browser verifies the origin certificate for the public domain. Passthrough cannot inspect paths, redirect requests, cache HTTPS, change Host/SNI, or apply HTTP access rules. Select POP TLS termination to use those features on HTTPS. With termination, HTTP and HTTPS origins are both supported; origin Host/SNI can be configured independently. Disabling origin certificate verification encrypts traffic without authenticating the origin. An HTTP-only origin requires a POP certificate to serve browser HTTPS.'],
 ['DNS and traffic routing','A customer subdomain can CNAME to its generated CDN hostname. The zone apex normally requires A/AAAA records, or flattening/ALIAS support from its authoritative DNS provider. Edgeplane publishes addresses in its configured CDN zone. Shared anycast IPs require working routing on the POPs; entering an IP does not announce BGP. Preserve the customer’s original origin address separately before changing DNS.'],
 ['PowerDNS setup','Use the PowerDNS Authoritative API URL and its api-key. A PowerDNS-Admin login page is not automatically an Authoritative API endpoint. Save & test checks connectivity and access; HTTP 401/403 indicates authentication or access policy problems. Confirm the server ID and managed zone exist.'],
 ['Nodes and services','Node service health and vhost deployment state are separate. Sync vhosts reconciles configuration. Reprovision services repairs service installation. Upgrade Agent only updates management code. Valid configuration changes use graceful NGINX reload and Varnish VCL activation. Review node activity and Jobs for failed operations.'],
 ['SSH sessions','Open a terminal using the configured SSH account. Minimize retains the session in the bottom dock while navigating. Click its node name to restore it. Full screen expands the terminal; Paste clipboard sends clipboard text to the shell. Closing the terminal, signing out, or reloading the browser ends the session.'],
 ['Monitoring and geography','Monitoring shows observed node health; sample times matter. Traffic reports aggregate request counts, bytes and cache results. Global geographic settings control MMDB installation, while each vhost must also enable geographic analytics. Unknown/private client IPs cannot be mapped. Full collection stores hourly history; Metrics only retains counters without history; Pause stops Supervisor collection.'],
 ['Customers and access','Customers manages customer records. Customer monitoring is available under Monitoring → Traffic using the customer filter. Users controls operator accounts and permissions; Preferences controls your account and display. Audit log records changes; Jobs tracks queued work; Logs provides operational diagnostics. Routing health and Topology show POP routing and relationships.'],
 ['Certificates, policies and settings','Certificates manages uploaded and managed certificates. Bind certificates to vhosts in TLS settings. Cache policies control TTL and bypass behavior; Rate limits controls request limits; Real IP defines trusted proxies; Headers defines request and response headers. Settings controls global runtime defaults.']
];
export default function OperatorHelp(){const [open,setOpen]=useState(false),[query,setQuery]=useState('');return <><button onClick={()=>setOpen(true)}>Help</button>{open&&<Modal title="Operator guide" close={()=>setOpen(false)} wide><div className="formbody operator-help"><input aria-label="Search operator guide" placeholder="Search features, DNS, TLS…" value={query} onChange={e=>setQuery(e.target.value)}/>{topics.filter(t=>t.join(' ').toLowerCase().includes(query.toLowerCase())).map(([title,text])=><details key={title} open={!!query}><summary>{title}</summary><p>{text}</p></details>)}</div></Modal>}</>}
