"""users preferences customers api tokens and traffic counters"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "2e82c5dac817"
down_revision = "20260909_immutable"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "api_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "traffic_buckets",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("vhost_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requests", sa.BigInteger(), nullable=False),
        sa.Column("bytes_sent", sa.BigInteger(), nullable=False),
        sa.Column("bytes_received", sa.BigInteger(), nullable=False),
        sa.Column("cache_hits", sa.BigInteger(), nullable=False),
        sa.Column("errors", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vhost_id"],
            ["vhosts.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "vhost_id", "country", "hour"),
    )
    op.create_index(op.f("ix_traffic_buckets_hour"), "traffic_buckets", ["hour"], unique=False)
    op.create_table(
        "traffic_counters",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("vhost_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("epoch", sa.String(length=36), nullable=False),
        sa.Column("observed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vhost_id"],
            ["vhosts.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "vhost_id", "country"),
    )
    op.add_column(
        "users",
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column("vhosts", sa.Column("customer_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_vhosts_customer_id"), "vhosts", ["customer_id"], unique=False)
    op.create_foreign_key(None, "vhosts", "customers", ["customer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vhosts", type_="foreignkey")
    op.drop_index(op.f("ix_vhosts_customer_id"), table_name="vhosts")
    op.drop_column("vhosts", "customer_id")
    op.drop_column("users", "preferences")
    op.drop_table("traffic_counters")
    op.drop_index(op.f("ix_traffic_buckets_hour"), table_name="traffic_buckets")
    op.drop_table("traffic_buckets")
    op.drop_table("api_tokens")
    op.drop_table("customers")
    # ### end Alembic commands ###
