import {useState,useEffect} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,type Row} from '../api';
import {Field,ErrorBox,Table} from '../components/ui';
export default function DNSSettings(){
 const client=useQueryClient();const settings=useQuery<Row>({queryKey:['dns-settings'],queryFn:()=>api('/settings/dns')}),records=useQuery<Row[]>({queryKey:['dns'],queryFn:()=>api('/dns')});
 const [form,setForm]=useState<Row>({api_url:'',auth_mode:'api_key',api_key:'',username:'',password:'',server_id:'localhost',zone:'edge.example.net',ttl:60}),[error,setError]=useState(''),[result,setResult]=useState<Row|null>(null);
 useEffect(()=>{if(settings.data)setForm({...form,...settings.data,api_key:'',password:''})},[settings.data]);const set=(k:string,v:any)=>setForm({...form,[k]:v});
 async function save(){const fields=['api_url','auth_mode','api_key','username','password','server_id','zone','ttl'];await api('/settings/dns','PUT',Object.fromEntries(fields.map(k=>[k,form[k]])));await client.invalidateQueries({queryKey:['dns-settings']})}
 return <><div className="pagehead"><div className="eyebrow">AUTHORITATIVE DNS</div><h1>PowerDNS connection</h1><p>Manage the provider connection and publish eligible edge addresses.</p></div><ErrorBox error={error||settings.error}/><section className="panel"><div className="formgrid"><Field label="PowerDNS API base URL" value={form.api_url} onChange={v=>set('api_url',v)}/><Field label="Server ID" value={form.server_id} onChange={v=>set('server_id',v)}/><Field label="Managed CDN zone" value={form.zone} onChange={v=>set('zone',v)}/><Field label="DNS TTL (seconds)" type="number" value={form.ttl} onChange={v=>set('ttl',Number(v))}/></div><label>Authentication<select value={form.auth_mode} onChange={e=>set('auth_mode',e.target.value)}><option value="api_key">API key · native PowerDNS</option><option value="basic">Username and password · compatible API gateway</option></select></label>{form.auth_mode==='api_key'?<Field label={settings.data?.has_api_key?'API key · leave blank to keep stored key':'API key'} type="password" value={form.api_key} onChange={v=>set('api_key',v)}/>:<><div className="formgrid"><Field label="Username" value={form.username} onChange={v=>set('username',v)}/><Field label={settings.data?.has_password?'Password · leave blank to keep stored password':'Password'} type="password" value={form.password} onChange={v=>set('password',v)}/></div><div className="notice">Basic mode works with a gateway that authenticates the REST API using username/password. Native PowerDNS REST uses X-API-Key; its web interface password alone does not replace the API key.</div></>}<div className="actions"><button className="primary" onClick={async()=>{try{await save();setResult({success:true,message:'Connection settings saved'});setError('')}catch(e){setError(String(e))}}}>Save connection</button><button onClick={async()=>{try{await save();setResult(await api('/dns/test-connection','POST'));setError('')}catch(e){setError(String(e))}}}>Save & test connection</button><button onClick={async()=>{try{const result=await api('/dns/reconcile','POST');setResult({success:true,message:'DNS reconciliation job queued: '+result.id})}catch(e){setError(String(e))}}}>Reconcile records</button></div>{result&&<div className={result.success?'notice':'error'}>{result.message||(result.success?'PowerDNS connection successful':'Connection failed')}</div>}</section><div className="sectionhead"><h2>Managed records</h2></div><Table rows={records.data||[]} columns={['name','type','values','status']}/></>
}
