import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Activity,RefreshCw,CheckCircle2,AlertCircle,ArrowUpRight} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api,type Row} from '../api';
import {Badge,ErrorBox,Table} from '../components/ui';
export default function Monitoring(){
 const client=useQueryClient(),query=useQuery<Row>({queryKey:['monitoring'],queryFn:()=>api('/monitoring'),refetchInterval:15000});
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);const data=query.data;
 return <><div className="pagehead"><div className="eyebrow">LIVE OPERATIONS</div><div className="sectionhead"><h1>Network monitoring</h1><button disabled={busy} onClick={async()=>{setBusy(true);try{await api('/monitoring/refresh','POST');setTimeout(()=>client.invalidateQueries({queryKey:['monitoring']}),5000)}catch(e){setError(String(e))}finally{setBusy(false)}}}><RefreshCw size={16}/>{busy?'Queuing…':'Check now'}</button></div><p>Agent health and revision drift checked every five minutes. Recent results refresh automatically.</p></div><ErrorBox error={error||query.error}/><div className="stats">{[['Active edges',data?.agents.length||0],['Healthy',data?.healthy||0],['Out of sync',data?.out_of_sync||0],['Desired revision',data?.desired_revision||0]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>Latest observed state</small></div>)}</div><div className="monitor-grid"><section><div className="sectionhead"><h2>Edge fleet</h2><Link to="/agents">Manage nodes <ArrowUpRight size={14}/></Link></div>{data?.agents.map((node:Row)=><Link to={'/agents?id='+node.id} className="monitor-node" key={node.id}><div className="node-symbol"><Activity size={20}/></div><div><b>{node.name}</b><small>{node.city||'Location not set'}</small></div><Badge value={node.status}/><div className="revision-status"><b>{node.applied_revision} / {node.desired_revision}</b><small>{node.out_of_sync?'OUT OF SYNC':'Synchronized'}</small></div></Link>)}</section><section className="panel"><h2>Latest events</h2><div className="event-feed">{data?.events.map((event:Row)=><div key={event.id}>{event.level==='ERROR'?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>}<div><p>{event.message}</p><small>{new Date(event.created_at).toLocaleString()}</small></div></div>)}</div></section></div></>
}
