import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Plus,Users as UsersIcon} from 'lucide-react';
import {api,type Row} from '../api';
import {ErrorBox,Field,Table,Modal,Badge} from '../components/ui';
export default function Users({me}:{me:Row}){
 const client=useQueryClient(),users=useQuery<Row[]>({queryKey:['users'],queryFn:()=>api('/users')});
 const [selected,setSelected]=useState<Row|null>(null),[create,setCreate]=useState(false),[form,setForm]=useState({username:'',password:'',role:'VIEWER',active:true}),[error,setError]=useState('');
 async function save(){try{if(create)await api('/users','POST',{username:form.username,password:form.password,role:form.role});else await api('/users/'+selected!.id,'PUT',{role:form.role,active:form.active});await client.invalidateQueries({queryKey:['users']});setSelected(null);setCreate(false)}catch(e){setError(String(e))}}
 return <><div className="pagehead"><div className="eyebrow">ACCESS CONTROL</div><div className="sectionhead"><h1>Users & roles</h1><button className="primary" onClick={()=>{setCreate(true);setForm({username:'',password:'',role:'VIEWER',active:true})}}><Plus size={16}/>Add user</button></div><p>Manage who can observe, operate and administer your CDN.</p></div><div className="rolecards">{[['ADMIN','Full control, security credentials and user administration.'],['OPERATOR','Manage vhosts, deployments, cache purges and node operations.'],['VIEWER','Read-only visibility into infrastructure and traffic.']].map(([role,description])=><div className="panel" key={role}><Badge value={role}/><p>{description}</p></div>)}</div><ErrorBox error={error||users.error}/><Table rows={users.data||[]} columns={['username','role','active','must_change_password','created_at']} onClick={row=>{setSelected(row);setForm({username:row.username,password:'',role:row.role,active:row.active})}}/>{(create||selected)&&<Modal title={create?'Create user':`Manage ${selected!.username}`} close={()=>{setCreate(false);setSelected(null)}}><div className="formbody">{create&&<Field label="Username" required value={form.username} onChange={username=>setForm({...form,username})}/>}<label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>VIEWER</option><option>OPERATOR</option><option>ADMIN</option></select></label>{!create&&<label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Account enabled</label>}<Field label={create?'Initial password · 12+ characters':'Reset password · leave empty to keep current'} value={form.password} type="password" onChange={password=>setForm({...form,password})}/>{!create&&form.password&&<button onClick={async()=>{try{await api(`/users/${selected!.id}/reset-password`,'POST',{password:form.password});await client.invalidateQueries();setSelected(null)}catch(e){setError(String(e))}}}>Reset password & revoke sessions</button>}<p>Password changes initiated by an administrator require the user to choose a new password at next login.</p><ErrorBox error={error}/></div><footer><button onClick={()=>{setCreate(false);setSelected(null)}}>Cancel</button><button className="primary" onClick={save}>Save user</button></footer></Modal>}</>
}
