import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Plus,Trash2} from 'lucide-react';
import {api,type Row} from '../api';
import {Field,ErrorBox,ListField,LabelText} from '../components/ui';
import CountrySelect from '../components/CountrySelect';

export default function VhostSecurity({data,set,tab}:{data:Row,set:(key:string,value:any)=>void,tab:string}){
 const [lookup,setLookup]=useState(''),[location,setLocation]=useState<Row|null>(null),[error,setError]=useState('');
 const customers=useQuery<Row[]>({queryKey:['customers'],queryFn:()=>api('/customers?limit=200')});
 const geo={mode:'off',countries:[],city_ids:[],block_unknown:false,...data.options.geo};
 const telemetry={mode:'full',geography:false,...data.options.analytics};
 const update=(key:string,value:any)=>set('options',{...data.options,[key]:value});

 if(tab==='Customer')return <><label>Customer<select value={data.customer_id||''} onChange={e=>set('customer_id',e.target.value||null)}><option value="">Unassigned</option>{customers.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>Every request and delivered byte is attributed to this vhost. Assign a customer to expose consolidated usage to your application.</p></>;

 if(tab==='Geography')return <><h3>Country & city traffic control</h3>{!data.certificate_id&&<div className="warning">These rules apply to HTTP traffic. To enforce geography on HTTPS, select a POP certificate in TLS. Encrypted passthrough cannot return an HTTP 403.</div>}<p>Rules use MaxMind country codes and GeoNames city IDs at NGINX. Geographic databases estimate location and are not an identity check.</p><label>Policy<select value={geo.mode} onChange={e=>update('geo',{...geo,mode:e.target.value})}><option value="off">No geographic restriction</option><option value="deny">Block selected countries / cities</option><option value="allow">Only allow selected countries / cities</option></select></label><CountrySelect values={geo.countries} onChange={v=>update('geo',{...geo,countries:v})}/><ListField label="GeoNames city IDs · comma separated" numeric values={geo.city_ids} onChange={v=>update('geo',{...geo,city_ids:v})}/><label className="check"><input type="checkbox" checked={geo.block_unknown} onChange={e=>update('geo',{...geo,block_unknown:e.target.checked})}/>Block unknown geographic locations</label><h3>Look up a client IP</h3><div className="inlineform"><input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="Client IP address"/><button onClick={async()=>{try{setLocation(await api('/geo/lookup?ip='+encodeURIComponent(lookup)));setError('')}catch(e){setError(String(e))}}}>Locate IP</button></div>{location&&<div className="notice">{location.country_name} · {location.city} · City ID: {location.city_id||'Unknown'}{location.city_id&&<button onClick={()=>update('geo',{...geo,city_ids:[...new Set([...geo.city_ids,location.city_id])]})}>Add city</button>}</div>}<ErrorBox error={error}/></>;

 if(tab==='Traffic')return <><h3>Traffic collection</h3><label>Per-vhost mode<select value={telemetry.mode} onChange={e=>update('analytics',{...telemetry,mode:e.target.value})}><option value="full">Counters + hourly history</option><option value="metrics">Metrics only</option><option value="off">Disable traffic collection</option></select></label><label className="check"><input type="checkbox" checked={telemetry.geography} onChange={e=>update('analytics',{...telemetry,geography:e.target.checked})}/>Record country-level traffic metrics</label><p>Geographic analytics requires the City database on every target edge. Disabling analytics does not disable geographic access rules.</p></>;

 const rules:Row[]=data.options.path_rules||[];
 const redirects:Row[]=data.options.redirect_rules||[];
 const routes:Row[]=data.options.origin_routes||[];
 return <>
  <h3>Path access rules</h3><p>Return 403 for a path, or allow only explicitly listed client networks. Matching deny rules take precedence.</p>
  {!data.certificate_id&&<div className="warning">HTTPS passthrough bypasses POP path rules and redirects because the path is encrypted. Select a POP certificate in TLS to enforce these rules on HTTPS. HTTP requests still use these rules.</div>}
  {rules.map((rule,i)=>{const change=(key:string,value:any)=>update('path_rules',rules.map((r,j)=>j===i?{...r,[key]:value}:r));return <div className="originform" key={i}><div className="sectionhead"><h3>Rule {i+1}</h3><button aria-label="Remove path rule" onClick={()=>update('path_rules',rules.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div><Field label="Path" value={rule.path} onChange={v=>change('path',v)}/><div className="formgrid"><label>Match<select value={rule.match} onChange={e=>change('match',e.target.value)}><option value="prefix">Path prefix</option><option value="exact">Exact path</option></select></label><label>Action<select value={rule.action} onChange={e=>change('action',e.target.value)}><option value="deny">403 Forbidden</option><option value="allow_ips">Only selected IPs</option></select></label></div>{rule.action==='allow_ips'&&<ListField label="Allowed IPs / CIDRs · one per line" multiline values={rule.cidrs||[]} onChange={v=>change('cidrs',v)}/>}</div>})}
  <button onClick={()=>update('path_rules',[...rules,{path:'/',match:'prefix',action:'deny',cidrs:[]}])}><Plus size={15}/>Add path rule</button>

  <h3>Path origin routing</h3><p>Send matching paths to a selected origin from the Origin tab. Unmatched paths use the normal origin pool; caching and security policy still apply.</p>
  {routes.map((route,i)=>{const change=(key:string,value:any)=>update('origin_routes',routes.map((r,j)=>j===i?{...r,[key]:value}:r));return <div className="originform" key={i}><div className="sectionhead"><h3>Origin route {i+1}</h3><button aria-label="Remove origin route" onClick={()=>update('origin_routes',routes.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div><Field label="Origin route path" value={route.path} onChange={v=>change('path',v)}/><div className="formgrid"><label><LabelText help="Exact matches one URL path; prefix matches every path beginning with these characters.">Match</LabelText><select value={route.match} onChange={e=>change('match',e.target.value)}><option value="prefix">Path prefix</option><option value="exact">Exact path</option></select></label><label><LabelText help="Choose an origin already configured in the Origin tab. Routes to one origin rather than the fallback pool.">Destination origin</LabelText><select value={route.origin_index} onChange={e=>change('origin_index',Number(e.target.value))}>{data.origins.map((origin:Row,j:number)=><option key={j} value={j}>{j+1} · {origin.host||'Unnamed origin'}</option>)}</select></label></div></div>})}
  <button disabled={!data.origins.length} onClick={()=>update('origin_routes',[...routes,{path:'/api/',match:'prefix',origin_index:0}])}><Plus size={15}/>Add origin route</button>

  <h3>HTTP 303 redirects</h3><p>Redirect a matching path to a fixed URL. For the entire vhost, use / with prefix matching. Access and country rules still apply first.</p>
  {redirects.map((rule,i)=>{const change=(key:string,value:any)=>update('redirect_rules',redirects.map((r,j)=>j===i?{...r,[key]:value}:r));return <div className="originform" key={i}><div className="sectionhead"><h3>Redirect {i+1}</h3><button aria-label="Remove redirect" onClick={()=>update('redirect_rules',redirects.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div><div className="formgrid"><Field label="Redirect path" value={rule.path} onChange={v=>change('path',v)}/><label>Match<select value={rule.match} onChange={e=>change('match',e.target.value)}><option value="exact">Exact path</option><option value="prefix">Path prefix</option></select></label></div><Field label="Redirect target URL" value={rule.target} onChange={v=>change('target',v)}/></div>})}
  <button onClick={()=>update('redirect_rules',[...redirects,{path:'/',match:'exact',target:'https://example.com/',status:303}])}><Plus size={15}/>Add 303 redirect</button>
 </>;
}
