import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Plus,Trash2} from 'lucide-react';
import {api,type Row} from '../api';
import {Field,ErrorBox,ListField} from '../components/ui';
export default function VhostSecurity({data,set,tab}:{data:Row,set:(key:string,value:any)=>void,tab:string}){
 const [lookup,setLookup]=useState(''),[location,setLocation]=useState<Row|null>(null),[error,setError]=useState('');
 const customers=useQuery<Row[]>({queryKey:['customers'],queryFn:()=>api('/customers?limit=200')});
 const geo={mode:'off',countries:[],city_ids:[],block_unknown:false,...data.options.geo};
 const telemetry={mode:'full',geography:false,...data.options.analytics};
 const update=(key:string,value:any)=>set('options',{...data.options,[key]:value});
 if(tab==='Customer')return <><label>Customer<select value={data.customer_id||''} onChange={e=>set('customer_id',e.target.value||null)}><option value="">Unassigned</option>{customers.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>Every request and delivered byte is attributed to this vhost. Assign a customer to expose consolidated usage to your application.</p></>;
 if(tab==='Geography')return <><h3>Country & city traffic control</h3><p>Rules use MaxMind country codes and GeoNames city IDs at NGINX. Geographic databases estimate location and are not an identity check.</p><label>Policy<select value={geo.mode} onChange={e=>update('geo',{...geo,mode:e.target.value})}><option value="off">No geographic restriction</option><option value="deny">Block selected countries / cities</option><option value="allow">Only allow selected countries / cities</option></select></label><ListField label="Country codes · comma separated, e.g. IR, DE" values={geo.countries} onChange={v=>update('geo',{...geo,countries:v.map(x=>x.toUpperCase())})}/><ListField label="GeoNames city IDs · comma separated" numeric values={geo.city_ids} onChange={v=>update('geo',{...geo,city_ids:v})}/><label className="check"><input type="checkbox" checked={geo.block_unknown} onChange={e=>update('geo',{...geo,block_unknown:e.target.checked})}/>Block unknown geographic locations</label><h3>Look up a client IP</h3><div className="inlineform"><input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="Client IP address"/><button onClick={async()=>{try{setLocation(await api('/geo/lookup?ip='+encodeURIComponent(lookup)));setError('')}catch(e){setError(String(e))}}}>Locate IP</button></div>{location&&<div className="notice">{location.country_name} · {location.city} · City ID: {location.city_id||'Unknown'}{location.city_id&&<button onClick={()=>update('geo',{...geo,city_ids:[...new Set([...geo.city_ids,location.city_id])]})}>Add city</button>}</div>}<ErrorBox error={error}/></>;
 if(tab==='Traffic')return <><h3>Traffic collection</h3><label>Per-vhost mode<select value={telemetry.mode} onChange={e=>update('analytics',{...telemetry,mode:e.target.value})}><option value="full">Counters + hourly history</option><option value="metrics">Metrics only</option><option value="off">Disable traffic collection</option></select></label><label className="check"><input type="checkbox" checked={telemetry.geography} onChange={e=>update('analytics',{...telemetry,geography:e.target.checked})}/>Record country-level traffic metrics</label><p>Geographic analytics requires the City database on every target edge. Disabling analytics does not disable geographic access rules.</p></>;
 const rules=data.options.path_rules||[];
 return <><h3>Path access rules</h3><p>Return 403 for a path, or allow only explicitly listed client networks. Matching deny rules take precedence.</p>{rules.map((rule:Row,i:number)=>{const change=(key:string,value:any)=>update('path_rules',rules.map((r:Row,j:number)=>j===i?{...r,[key]:value}:r));return <div className="originform" key={i}><div className="sectionhead"><h3>Rule {i+1}</h3><button aria-label="Remove path rule" onClick={()=>update('path_rules',rules.filter((_:any,j:number)=>j!==i))}><Trash2 size={14}/></button></div><Field label="Path" value={rule.path} onChange={v=>change('path',v)}/><div className="formgrid"><label>Match<select value={rule.match} onChange={e=>change('match',e.target.value)}><option value="prefix">Path prefix</option><option value="exact">Exact path</option></select></label><label>Action<select value={rule.action} onChange={e=>change('action',e.target.value)}><option value="deny">403 Forbidden</option><option value="allow_ips">Only selected IPs</option></select></label></div>{rule.action==='allow_ips'&&<ListField label="Allowed IPs / CIDRs · one per line" multiline values={rule.cidrs||[]} onChange={v=>change('cidrs',v)}/>}</div>})}<button onClick={()=>update('path_rules',[...rules,{path:'/',match:'prefix',action:'deny',cidrs:[]}])}><Plus size={15}/>Add path rule</button></>
}
